version: 2
updates:
- package-ecosystem: cargo
  directory: "/rust/libdnf-sys"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/rust"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
