branches:
    - master
    - auto
    - try

context: f25-build-check

required: true

container:
    image: registry.fedoraproject.org/fedora:25

packages:
  - git

tests:
  - ci/ci-commitmessage-submodules.sh
  - ci/codestyle.sh
  - ci/build-check.sh

timeout: 30m

artifacts:
    - test-suite.log

---

inherit: true

context: f26-build-check

required: false

container:
    image: registry.fedoraproject.org/fedora:26

tests:
  # updates-source mirrors are being flaky
  - sed -i '/metalink=.*updates-released-source.*/ d' /etc/yum.repos.d/fedora-updates.repo
  - sed -i '/SRPMS/ s/^#baseurl/baseurl/' /etc/yum.repos.d/fedora-updates.repo
  - ci/build-check.sh

---

inherit: true

context: c7-build

required: true

container:
  image: registry.centos.org/centos/centos:7

extra-repos:
  - name: atomic-centos-continuous
    baseurl: https://ci.centos.org/artifacts/sig-atomic/rdgo/centos-continuous/build
    gpgcheck: 0

# XXX: integrate better with ci/ scripts
tests:
  - yum-builddep -y rpm-ostree
  - yum install -y polkit-devel
  - yum install -y make
  - source ci/libbuild.sh && build

timeout: 15m

---

inherit: true

context: f25-vmcheck

required: true

cluster:
  hosts:
    - name: vmcheck1
      distro: fedora/25/atomic
    - name: vmcheck2
      distro: fedora/25/atomic
    - name: vmcheck3
      distro: fedora/25/atomic
  container:
    image: registry.fedoraproject.org/fedora:25

env:
  HOSTS: vmcheck1 vmcheck2 vmcheck3

tests:
  - ./ci/build.sh
  - make vmcheck

artifacts:
  - vmcheck

# We really need to work on getting this down:
# https://github.com/projectatomic/rpm-ostree/issues/662
timeout: 80m

---

inherit: true

context: f26-vmcheck

required: false

cluster:
  hosts:
    - name: vmcheck
      distro: fedora/26/atomic
  container:
    image: registry.fedoraproject.org/fedora:26

env:
  HOSTS: vmcheck

tests:
  # updates-source mirrors are being flaky
  - sed -i '/metalink=.*updates-released-source.*/ d' /etc/yum.repos.d/fedora-updates.repo
  - sed -i '/SRPMS/ s/^#baseurl/baseurl/' /etc/yum.repos.d/fedora-updates.repo
  - ./ci/build.sh
  - make vmcheck

---

branches:
  - master
  - auto
  - try

# NB: when bumping 25 here, also bump fedora.repo, compose script, and
# fedora-base.json

context: f25-compose

build: false

timeout: 30m

required: true

# This test case wants an "unprivileged container with bubblewrap",
# which we don't have right now; so just provision a VM and do a
# docker --privileged run.
host:
  distro: fedora/25/atomic

# copy yum.repos.d to get any injected repos from the host, which
# will point to a closer mirror
tests:
  - docker run --privileged --rm
    -e RPMOSTREE_COMPOSE_TEST_USE_HOST_REPO=1
    -v /etc/yum.repos.d:/etc/yum.repos.d.host:ro
    -v $(pwd):/srv/code -w /srv/code
    registry.fedoraproject.org/fedora:25 /bin/sh -c
    "cp -fv /etc/yum.repos.d{.host/*.repo,} &&
     ./ci/build.sh && make install && ./tests/compose"

artifacts:
  - compose.log
