branches:
    - master
    - auto
    - try

context: f26-primary

required: true

cluster:
  hosts:
    - name: vmcheck1
      distro: fedora/26/atomic
    - name: vmcheck2
      distro: fedora/26/atomic
    - name: vmcheck3
      distro: fedora/26/atomic
  container:
    image: registry.fedoraproject.org/fedora:26

packages:
  - git
  - rsync

env:
  HOSTS: vmcheck1 vmcheck2 vmcheck3

tests:
  - ci/ci-commitmessage-submodules.sh
  - ci/codestyle.sh
  - ci/build-check.sh
  - make vmcheck

timeout: 60m

artifacts:
  - test-suite.log
  - vmcheck

---

inherit: true

context: c7-primary

required: true

cluster:
  hosts:
    - name: vmcheck1
      distro: centos/7/atomic/alpha
    - name: vmcheck2
      distro: centos/7/atomic/alpha
    - name: vmcheck3
      distro: centos/7/atomic/alpha
  container:
    image: registry.centos.org/centos/centos:7

extra-repos:
  - name: atomic-centos-continuous
    baseurl: https://ci.centos.org/artifacts/sig-atomic/rdgo/centos-continuous/build
    gpgcheck: 0

tests:
  - yum install -y epel-release
  - ci/build-check.sh
  - make vmcheck

---

branches:
  - master
  - auto
  - try

# NB: when bumping 26 here, also bump fedora.repo, and compose script

context: f26-compose

build: false

timeout: 30m

required: true

# This test case wants an "unprivileged container with bubblewrap",
# which we don't have right now; so just provision a VM and do a
# docker --privileged run.
host:
  distro: fedora/26/atomic

# Copy yum.repos.d to get any injected repos from the host, which
# will point to a closer mirror.  Note we substitute $releasever
# since https://github.com/projectatomic/rpm-ostree/pull/875
tests:
  - docker run --privileged --rm
    -e RPMOSTREE_COMPOSE_TEST_USE_HOST_REPO=1
    -v /etc/yum.repos.d:/etc/yum.repos.d.host:ro
    -v $(pwd):/srv/code -w /srv/code
    registry.fedoraproject.org/fedora:26 /bin/sh -c
    "cp -fv /etc/yum.repos.d{.host/*.repo,} &&
     for x in /etc/yum.repos.d/*.repo; do sed -i -e 's,\$releasever,26,' \$x; done && \
     ./ci/build.sh && make install && ./tests/compose"

artifacts:
  - compose.log
