branches:
    - master
    - auto
    - try

context: f25-build-check

required: true

container:
    image: registry.fedoraproject.org/fedora:25

packages:
  - git

tests:
  - ci/ci-commitmessage-submodules.sh
  - ci/build-check.sh

timeout: 30m

artifacts:
    - test-suite.log

---

inherit: true

context: vmcheck

required: true

cluster:
  hosts:
    - name: vmcheck1
      distro: fedora/25/atomic
    - name: vmcheck2
      distro: fedora/25/atomic
    - name: vmcheck3
      distro: fedora/25/atomic
  container:
    image: registry.fedoraproject.org/fedora:25

tests:
  - ./ci/build.sh
  - make vmcheck HOSTS="vmcheck1 vmcheck2 vmcheck3"

artifacts:
  - vmcheck

# We really need to work on getting this down:
# https://github.com/projectatomic/rpm-ostree/issues/662
timeout: 80m

---

# NB: when bumping 25 here, also bump fedora.repo, compose script, and
# fedora-base.json

context: compose
build: false
timeout: 30m

# This test case wants an "unprivileged container with bubblewrap",
# which we don't have right now; so just provision a VM and do a
# docker --privileged run.
host:
  distro: fedora/25/atomic

# mount yum.repos.d to get any injected repos from the host, which
# will point to a closer mirror
tests:
  - >
      docker run --privileged --rm
      -e RPMOSTREE_COMPOSE_TEST_USE_HOST_REPO=1
      -v /etc/yum.repos.d:/etc/yum.repos.d:ro
      -v $(pwd):/srv/code
      registry.fedoraproject.org/fedora:25 /bin/sh -c
      "cd /srv/code && ./ci/build.sh && make install && ./tests/compose"

artifacts:
  - compose.log
