branches:
    - master
    - auto
    - try

context: f25-build-check

required: true

container:
    image: registry.fedoraproject.org/fedora:25

packages:
  - git

tests:
  - ci/ci-commitmessage-submodules.sh
  - ci/build-check.sh

timeout: 30m

artifacts:
    - test-suite.log

---

inherit: true

context: vmcheck

required: true

cluster:
  hosts:
    - name: vmcheck1
      distro: fedora/25/atomic
    - name: vmcheck2
      distro: fedora/25/atomic
    - name: vmcheck3
      distro: fedora/25/atomic
  container:
    image: registry.fedoraproject.org/fedora:25

tests:
  - ./ci/build.sh
  - make vmcheck HOSTS="vmcheck1 vmcheck2 vmcheck3"

artifacts:
  - vmcheck

# We really need to work on getting this down:
# https://github.com/projectatomic/rpm-ostree/issues/662
timeout: 80m

---

context: compose
build: false
timeout: 30m

# This test case wants an "unprivileged container with bubblewrap",
# which we don't have right now; so just provision a VM and do a
# docker --privileged run.
host:
  distro: fedora/25/atomic

tests:
  - >
      docker run --privileged -v $(pwd):/srv/code --rm
      registry.fedoraproject.org/fedora:25 /bin/sh -c "cd /srv/code && ./ci/build.sh && make install && ./tests/compose"

artifacts:
  - compose.log
