branches:
  - master
  - auto
  - try

# NB: when bumping 29 here, also bump compose script

context: f29-compose1

build: false

timeout: 35m

# This test case wants an "unprivileged container with bubblewrap",
# which we don't have right now; so just provision a VM and do a
# docker --privileged run.
host:
  distro: fedora/29/atomic
  # Compose tests are slow and should be parallelized
  specs:
    cpus: 4

env:
  RPMOSTREE_COMPOSE_TEST_FILTER: odd

# Copy yum.repos.d to get any injected repos from the host, which
# will point to a closer mirror.  Note we substitute $releasever
# since https://github.com/projectatomic/rpm-ostree/pull/875
tests:
  - docker run --privileged --rm
    -e RPMOSTREE_COMPOSE_TEST_FILTER
    -e RPMOSTREE_COMPOSE_TEST_USE_REPOS=/etc/yum.repos.d.host
    -v /etc/yum.repos.d:/etc/yum.repos.d.host:ro
    -v $(pwd):/srv/code -w /srv/code
    registry.fedoraproject.org/fedora:29 /bin/sh -c
    "cp /etc/yum.repos.d.host/* /etc/yum.repos.d/ && ./ci/build.sh && make install && ./tests/compose"

artifacts:
  - test-compose-logs

---

inherit: true
context: f29-compose2
env:
  RPMOSTREE_COMPOSE_TEST_FILTER: even
