branches:
    - master
    - auto
    - try

context: check

container:
    image: projectatomic/ostree-tester

env:
    CFLAGS: '-fsanitize=undefined'

build:
    config-opts: >
      --prefix=/usr
      --libdir=/usr/lib64
      --enable-installed-tests
      --enable-gtk-doc

packages:
  - python-sphinx
  - createrepo_c
  - gperf
  - rpm-build
  - bubblewrap
  - python-devel
  - check-devel
  - pkgconfig(ostree-1)
  - pkgconfig(libgsystem)
  - pkgconfig(librepo)
  - pkgconfig(libsolv)
  - pkgconfig(rpm)
  - pkgconfig(json-glib-1.0)
  - pkgconfig(expat)
  - cmake
  - gtk-doc

tests:
    - make check
    - gnome-desktop-testing-runner rpm-ostree
    - sudo --user=testuser gnome-desktop-testing-runner rpm-ostree

timeout: 30m

artifacts:
    - test-suite.log

---

inherit: true

context: Clang

env:
    CC: 'clang'
    CFLAGS: '-Werror=unused-variable'

tests:
artifacts:

---

inherit: true

context: vmcheck

cluster:
  hosts:
    - name: vmcheck
      distro: fedora/24/atomic
  container:
    image: projectatomic/ostree-tester

tests:
  - cp .redhat-ci.ssh-config ssh-config
  - make vmcheck

artifacts:
  - vmcheck.log

---
context: compose
build: false
timeout: 30m

# This test case wants an "unprivileged container with bubblewrap",
# which we don't have right now; so just provision a VM and do a
# docker --privileged run.
host:
  distro: centos/7/atomic/alpha

tests:
  # Yes, we're duplicating the build dependencies *again*!  Woo!
  - docker run --privileged -v $(pwd):/srv/code --rm projectatomic/ostree-tester /bin/sh -c 'yum -y install python-sphinx createrepo_c gperf rpm-build bubblewrap python-devel check-devel "pkgconfig(ostree-1)" "pkgconfig(libgsystem)" "pkgconfig(librepo)" "pkgconfig(libsolv)" "pkgconfig(rpm)" "pkgconfig(json-glib-1.0)" "pkgconfig(expat)" cmake gtk-doc && cd /srv/code && env NOCONFIGURE=1 ./autogen.sh && ./configure --prefix=/usr --libdir=/usr/lib64 && make && make install && ./tests/compose'
