branches:
    - master
    - auto
    - try

context: check

required: true

container:
    image: projectatomic/rpm-ostree-tester

env:
    CFLAGS: '-fsanitize=undefined'

build:
    config-opts: >
      --prefix=/usr
      --libdir=/usr/lib64
      --enable-installed-tests
      --enable-gtk-doc

tests:
    - make check
    - gnome-desktop-testing-runner rpm-ostree
    - sudo --user=testuser gnome-desktop-testing-runner rpm-ostree

timeout: 30m

artifacts:
    - test-suite.log
    - config.log

---

inherit: true

context: Clang

required: true

env:
    CC: 'clang'
    CFLAGS: '-Werror=unused-variable'

build:
    config-opts: >
      --prefix=/usr
      --libdir=/usr/lib64
      --enable-installed-tests
      --enable-gtk-doc
      --enable-new-name

tests:
artifacts:

---

inherit: true

context: vmcheck

required: true

cluster:
  hosts:
    - name: vmcheck1
      distro: fedora/25/atomic
    - name: vmcheck2
      distro: fedora/25/atomic
    - name: vmcheck3
      distro: fedora/25/atomic
  container:
    image: projectatomic/rpm-ostree-tester

tests:
  - make vmcheck HOSTS="vmcheck1 vmcheck2 vmcheck3"

artifacts:
  - vmcheck

# We really need to work on getting this down:
# https://github.com/projectatomic/rpm-ostree/issues/662
timeout: 80m

---

context: compose
build: false
timeout: 30m

# This test case wants an "unprivileged container with bubblewrap",
# which we don't have right now; so just provision a VM and do a
# docker --privileged run.
host:
  distro: fedora/25/atomic

tests:
  - >
      docker run --privileged -v $(pwd):/srv/code --rm
      projectatomic/rpm-ostree-tester /bin/sh -c "
      cd /srv/code &&
      env NOCONFIGURE=1 ./autogen.sh &&
      ./configure --prefix=/usr --libdir=/usr/lib64 &&
      make &&
      make install &&
      dnf update -y bubblewrap &&
      ./tests/compose
      "

artifacts:
  - compose.log
