#!/bin/sh
while true; do
   path=logs/$(date +%Y/%m/%d/%H)
   mkdir -p ${path}
   echo "Starting run, logging to ${path}"
   $(dirname $0)/fedostree-make-trees > ${path}/log.txt 2>&1
   echo "Complete, sleep 1h"
   sleep 1h
done
