#!/usr/bin/env bash

set -e
set -x

DEFAULT_ENABLED_REPOS="--enablerepo=fedora --enablerepo=updates --enablerepo=walters-nss-altfiles"
DEFAULT_OS_ARGS="--os=fedora --os-version=20"
DEFAULT_PACKAGES="kernel ostree fedora-release lvm2 btrfs-progs e2fsprogs"

if test -f ./fedostree.conf; then
    . ./fedostree.conf
fi

docommit() {
    name=$1
    shift
    echo "Starting rpm-ostree run at" $(date)
    rpm-ostree --repo=repo ${ENABLED_REPOS:-${DEFAULT_ENABLED_REPOS}} ${OS_ARGS:-${DEFAULT_OS_ARGS}} create "${name}" ${PACKAGES:-${DEFAULT_PACKAGES}} "$@" > log-${name}.txt 2>&1
    echo "Completed rpm-ostree run at" $(date)
}

docommit minimal @core
docommit standard @core @standard
docommit standard-docker-io @core @standard docker-io
docommit standard-freeipa-server @core @standard @freeipa-server
docommit standard-jbossas @core @standard @jbossas
docommit gnome-desktop-core @gnome-desktop
docommit gnome-desktop-environment @firefox @gnome-desktop @gnome-games @epiphany @libreoffice
