---
- hosts: all
  gather_facts: no
  become: yes
  tasks:

    # if we're not already using the CAHC box, then add the
    # remote to make it easier for the user to rebase later
    - name: add CAHC ostree remote
      command: >
        ostree remote add --set=gpg-verify=false centos-atomic-continuous
        https://ci.centos.org/artifacts/sig-atomic/rdgo/centos-continuous/ostree/repo/
      args:
        creates: /etc/ostree/remotes.d/centos-atomic-continuous.conf

    # We generate a valid ssh-config here that libvm.sh can
    # make use of. This also requires making sure the root
    # user can be ssh'ed in directly.

    # set up auth key
    - file: state=directory mode=0600 path=/root/.ssh
    - command: cp .ssh/authorized_keys /root/.ssh

    # make sure root account is unlocked
    - name: unlock root account
      command: passwd -u root

    # generate ssh config
    - name: generate config
      local_action: shell vagrant ssh-config > ../ssh-config
      become: no

    - name: make sure user in config is root
      local_action: lineinfile
        dest=../ssh-config
        regexp='^( *User) .*$'
        line='\1 root'
        backrefs=yes
      become: no
