---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: generate config
      local_action: shell vagrant ssh-config > ../ssh-config
      become: no

    # The test suite requires direct ssh to root.
    - file: state=directory mode=0600 path=/root/.ssh
    - copy: remote_src=True src=/home/vagrant/.ssh/authorized_keys dest=/root/.ssh/authorized_keys
    # make sure root account is unlocked
    - name: unlock root account
      shell:
        cmd: 'passwd -u root && touch /root/.unlocked'
        creates: /root/.unlocked

    - command: rpm -q fuse-sshfs
      register: rpmq_fuse_sshfs
      changed_when: False
      failed_when: False

    - command: rpm-ostree install fuse-sshfs
      when: rpmq_fuse_sshfs.rc != 0
