# This Dockerfile generates a container image that installs a build from git into
# a Fedora CoreOS image.
FROM quay.io/coreos-assembler/fcos-buildroot:testing-devel as builder
WORKDIR /src
COPY . .
RUN ./ci/build.sh && make install DESTDIR=$(pwd)/install && tar -C install -czf /srv/install.tar .

FROM quay.io/fedora/fedora-coreos:testing-devel
COPY --from=builder /srv/install.tar /tmp
RUN tar -xvf /tmp/install.tar && ostree container commit 
