#!/bin/bash
# Verify upgrades pulling from remote (authenticated) registries.
## kola:
##   timeoutMin: 30
##   tags: "needs-internet"
#
# Copyright (C) 2022 Red Hat, Inc.

set -xeuo pipefail

. /usr/lib/coreos-assembler/tests/kola/rpm-ostree/utils.sh

cd $(mktemp -d)

case "${AUTOPKGTEST_REBOOT_MARK:-}" in
  "")
    expected_image=$(cat /etc/target-image)
    booted_image=$(rpm-ostree status --json | jq -r '.deployments[0]["container-image-reference"]')
    
    test "$expected_image" = "$booted_image"

    systemctl mask --now zincati

    rpm-ostree upgrade >out.txt
    grep -qF 'No upgrade available' out.txt

    rpm -q moby-engine
    test '!' -f /etc/somenewfile

    # test with new rpm-ostree
    do_testing

    upgrade_image=$(cat /etc/upgrade-image)
    rpm-ostree rebase ${upgrade_image}
    /tmp/autopkgtest-reboot 1
    ;;
  "1")
    expected_image=$(cat /etc/upgrade-image)
    booted_image=$(rpm-ostree status --json | jq -r '.deployments[0]["container-image-reference"]')
    test "$expected_image" = "$booted_image"

    rpm-ostree upgrade >out.txt
    grep -qF 'No upgrade available' out.txt

    if rpm -q moby-engine 2>/dev/null; then
      echo "found package expected to be removed"
      exit 1
    fi
    test -f /etc/somenewfile

    do_checking

    echo "ok e2e upgrade"
    ;;
  *) echo "unexpected mark: ${AUTOPKGTEST_REBOOT_MARK}"; exit 1;;
esac
