FROM quay.io/fedora/fedora-bootc:41 as rootfs
RUN <<EORUN
set -xeuo pipefail
mkdir -p /var/lib/rpm-state
# Remove some high level superfulous stuff
dnf -y remove sos NetworkManager-tui vim nano
# We don't want any python, and we don't need rpm-ostree either.
dnf -y remove python3 rpm-ostree{,-libs}
dnf clean all
rm /var/lib/rpm -rf
bootc container lint
EORUN

# Note that the GHA flow in ci.yml injects a binary from C9S.
FROM quay.io/centos-bootc/centos-bootc:stream9 as builder
RUN --mount=type=bind,rw=true,src=.,dst=/buildcontext,bind-propagation=shared \
    --mount=from=rootfs,dst=/rootfs <<EORUN
set -xeuo pipefail
# Pull in the binary we just built; if you're doing this locally you'll want
# to e.g. run `podman build -v target/release/rpm-ostree:/ci/rpm-ostree`.
install /ci/rpm-ostree /usr/bin/
rm /buildcontext/out.oci -rf
rpm-ostree experimental compose build-chunked-oci --bootc --format-version=1 \
           --rootfs=/rootfs --output /buildcontext/out.oci
EORUN

FROM oci:./out.oci
# Need to reference builder here to force ordering. But since we have to run
# something anyway, we might as well cleanup after ourselves.
RUN --mount=type=bind,from=builder,src=.,target=/var/tmp \
    --mount=type=bind,rw=true,src=.,dst=/buildcontext,bind-propagation=shared rm /buildcontext/out.oci -rf           
