#! /bin/bash

# run a GTest in tap mode. The test binary is passed as $1

srcd=$(cd $(dirname $1) && pwd)
bn=$(basename $1)
tempdir=$(mktemp -d)
function cleanup () {
    if test -z "${TEST_SKIP_CLEANUP:-}"; then
	      if test -f ${test_tmpdir}/.test; then
            rm "${tempdir}" -rf
        fi
    else
	      echo "Skipping cleanup of ${test_tmpdir}"
    fi
}
trap cleanup EXIT
cd ${tempdir}
${srcd}/${bn} -k --tap
