# -*- mode: Makefile -*-

include Makefile.dist-packaging


docker-local: rpm
	rm docker -rf
	mkdir -p docker
	cp x86_64/$(PKG_VER)*.x86_64.rpm docker/$(PACKAGE).rpm
	sed \
	-e s,\@PACKAGE\@,$(PACKAGE).rpm,g \
	< Dockerfile.in > docker/Dockerfile
	(cd docker && docker build -t cgwalters/rpm-ostree .)
