#!/usr/bin/env python
#
# Copyright (C) 2012,2013 Colin Walters <walters@verbum.org>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

import os
import sys
import subprocess
import tempfile
import StringIO

sizeMb = 8 * 1024;
bootMb = 200;
swapMb = 500;

refname = sys.argv[1];
diskname = refname.replace('/', '-') + '.qcow2';

if not os.path.exists(diskname):
    tmpname = diskname + '.tmp'
    if os.path.exists(tmpname): os.unlink(tmpname)
    partconfig_path = 'partconfig.txt'
    f = open(partconfig_path, 'w')
    f.write('''launch
part-add /dev/sda p 64 409663
part-add /dev/sda p 409664 540735
part-add /dev/sda p 540736 16777215
part-set-bootable /dev/sda 1 true
mkfs ext4 /dev/sda1
set-e2label /dev/sda1 gnostree-boot
mkswap-L gnostree-swap /dev/sda2
mkfs ext4 /dev/sda3
set-e2label /dev/sda3 gnostree-root
mount /dev/sda3 /
mkdir /boot''')
    f.close()
    subprocess.check_call(['qemu-img', 'create', '-f', 'qcow2', tmpname, '' + str(sizeMb) + 'M'])
    subprocess.check_call(['guestfish', '-a', tmpname, '--rw'], stdin=open(partconfig_path))

if not os.path.isdir('mnt'):
    os.mkdir('mnt')
subprocess.check_call(['guestmount', '-a', tmpname, '--rw', '-m', '/dev/sda3', '-m', '/dev/sda1:/boot', 'mnt'])

admin_cmd = ['ostree', 'admin', '--sysroot=mnt']
subprocess.check_call(admin_cmd + ['init-fs', 'mnt'])
