[package]
name = "rpmostree-bindgen"
version = "0.1.0"
authors = ["Colin Walters <walters@verbum.org>"]

[dependencies]
cbindgen = "0.16.0"

# Might as well keep these from the main Rust source
[profile.release]
panic = "abort"
debug = true
