---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container: registry.ci.openshift.org/coreos/fcos-buildroot:testing-devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # https://github.com/actions/checkout/issues/760
      - name: Mark git checkout as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Codestyle
        run: ./ci/codestyle.sh
      - name: Build
        run: ./ci/build.sh && make install DESTDIR=$(pwd)/install && tar -C install -czf install.tar .
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: install.tar
          path: install.tar
  integration:
    name: "Container Integration"
    needs: build
    runs-on: ubuntu-latest
    container: quay.io/coreos-assembler/fcos:testing-devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: install.tar
      - name: Install
        run: tar -C / -xzvf install.tar
      - name: Integration tests
        run: ./ci/test-container.sh
  compose:
    name: "Compose tests"
    needs: build
    runs-on: ubuntu-latest
    container:
      image: registry.ci.openshift.org/coreos/coreos-assembler:latest
      options: "--user root --privileged -v /var/tmp:/var/tmp"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install test dependencies
        run: ./ci/install-test-deps.sh
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: install.tar
      - name: Install
        run: tar -C / -xzvf install.tar
      - name: Integration tests
        run: env TMPDIR=/var/tmp JOBS=3 ./tests/compose.sh
