#!/bin/bash
## kola:
##  timeoutMin: 30  # We reboot etc.
##  tags: "needs-internet"  # We fetch from the main registry
# 
# Copyright (C) 2022 Red Hat, Inc.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

set -euo pipefail

. ${KOLA_EXT_DATA}/libtest.sh

set -x

libtest_prepare_offline
cd "$(mktemp -d)"

image=quay.io/fedora/fedora-coreos
image_tag=testing-devel
digest=$(skopeo inspect -n docker://$image:$image_tag | jq -r .Digest)
image_pull=ostree-remote-registry:fedora:$image@$digest

systemctl mask --now zincati
# Test for https://github.com/ostreedev/ostree/issues/3228
rpm-ostree kargs --append "foo=\"a b c\""
rpm-ostree kargs > kargs.txt
assert_file_has_content_literal kargs.txt "foo=\"a b c\""
# also test custom origin stuff
rpm-ostree rebase "${image_pull}" --custom-origin-description "Fedora CoreOS $image_tag stream" --custom-origin-url "$image:$image_tag"
rpm-ostree status > status.txt
assert_file_has_content_literal status.txt "$image:$image_tag" "Fedora CoreOS $image_tag stream"
rpm-ostree upgrade
# This provokes
# https://github.com/coreos/rpm-ostree/issues/4107
podman image rm -f shouldnotexist || true
test -d /run/containers
# https://github.com/coreos/rpm-ostree/issues/4176
rpm-ostree upgrade --check > err.txt || rc=$?
assert_file_has_content_literal err.txt 'No updates available.'
assert_streq "${rc}" 77
rpm-ostree upgrade

echo "ok upgrade after podman"
