#!/bin/bash
# kola: { "tags": "needs-internet" }
# Test https://github.com/coreos/rpm-ostree/pull/2420
# i.e. using overrides from Fedora Infrastructure tools (koji/bodhi)
set -euo pipefail

. ${KOLA_EXT_DATA}/libtest.sh
cd $(mktemp -d)

set -x

# bodhi update for rpm-ostree (Fedora 33)
rpm-ostree override replace https://bodhi.fedoraproject.org/updates/FEDORA-2021-e55da2fc78
rpm-ostree status > status.txt
rpm-ostree cleanup -p
# A build directly via Koji (this is rpm-ostree-2021.1-2.fc33 - FIXME change
# this to pull latest tagged...which would require learning more of the Koji API
# *or* injecting it from the build container)
rpm-ostree override replace https://koji.fedoraproject.org/koji/buildinfo?buildID=1671410

echo "ok"
