#!/bin/bash
#
# Copyright (C) 2021 Red Hat Inc.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

set -euo pipefail

. ${KOLA_EXT_DATA}/libtest.sh

set -x

rpm-ostree deploy --ex-nosetuid=true
rpm-ostree ex apply-live  # yep it works!

if rpm -e bash 2>out.txt; then
    fatal "rpm -e worked"
fi

list="$(find /usr /etc -type f -perm /4000 -o -type f -perm /2000)"
if [[ -n "${list}" ]]; then
    find /usr /etc -type f -perm /4000 -print0 -o -type f -perm /2000 -print0 | xargs -0 ls -al
    fatal "found files with setuid or setgid permissions"
fi
echo "ok setnosuid no setuid or setgid files found"

rpm-ostree deploy --ex-nosetuid=false
rpm-ostree ex apply-live --allow-replacement
list="$(find /usr /etc -type f -perm /4000 -o -type f -perm /2000)"
if [[ -z "${list}" ]]; then
    fatal "found no files with setuid or setgid permissions"
fi
echo "ok setnosuid undo"
